Added language starting with v to dropdown file
chilarai/list-of-programming-languages pull request #130
Opened 2022-10-06 04:04 UTC by shubhamburad

2022-10-06 04:24 UTC, chilarai requested changes
Please do yhe required changes

2022-10-06 04:24 UTC, chilarai commented on A-Z-dropdown.html
> +        <option value="Viper (Ethereum/Ether (ETH))">Visual Prolog</option>
I can still see Visual Prolog in the name. Also, viper should have been Vyper. Isn't it?

2022-10-08 14:58 UTC, closed without merging

2022-10-09 04:06 UTC, shubhamburad commented on A-Z-dropdown.html
> +        <option value="Viper (Ethereum/Ether (ETH))">Visual Prolog</option>
Officialy it should be viper so can i raise pr again and can you please approve it?

2022-10-09 04:59 UTC, chilarai commented on A-Z-dropdown.html
> +        <option value="Viper (Ethereum/Ether (ETH))">Visual Prolog</option>
@Shrutiswift has already added that in PR #132. Thanks