Added letter V language and made W section
chilarai/list-of-programming-languages pull request #79
Opened 2022-10-01 12:54 UTC by viper-devil

W and V was mixed so i made seperate section for it and added a new language in V

2022-10-01 13:00 UTC, chilarai commented on A-Z-checkboxes.html
> +<label for="visual_lisp"> Velato </label><br />
I am unfamiliar with it but can you call Visual Lisp Velato?

2022-10-01 13:14 UTC, viper-devil commented on A-Z-checkboxes.html
> +<label for="visual_lisp"> Velato </label><br />
yes we can sorry i will correct it now

2022-10-02 05:14 UTC, chilarai approved these changes
Please do this change

2022-10-02 05:14 UTC, chilarai commented on A-Z-checkboxes.html
> +<label for="axum">ArnoldC</label><br />
Please change the label here

2022-10-02 05:15 UTC, chilarai requested changes
Please do the changes as mentioned

2022-10-02 08:12 UTC, chilarai approved these changes
Thanks

2022-10-02 08:12 UTC, merged