added programming languages with 'G' and [...]
chilarai/list-of-programming-languages pull request #94
Opened 2022-10-01 18:28 UTC by gabrielsozinho

fix programming languages with 'S'

2022-10-01 18:53 UTC, gabrielsozinho commented
@chilarai is this ok?

2022-10-02 03:46 UTC, chilarai requested changes
Please fix these issues first

2022-10-02 03:46 UTC, chilarai commented on A-Z-dropdown.html
> +<option value="inform">Groovy (Apache Groovy)</option>
option value is different to name

2022-10-02 03:46 UTC, chilarai commented on A-Z-dropdown.html
>  <option value="s3">S3</option>
why do we have dummy values here

2022-10-02 11:56 UTC, gabrielsozinho commented on A-Z-dropdown.html
>  <option value="s3">S3</option>
I didn't add it, I just corrected it as it was before. The languages ​​were with S (`option`s) but not with the `<select>` tag. Anyway, I'll fix it.

2022-10-02 12:03 UTC, gabrielsozinho commented on A-Z-dropdown.html
>  <option value="s3">S3</option>
@chilarai These are not dummy values.
![image](https://user-images.githubusercontent.com/90806505/193452972-47e88900-d93f-4083-a465-f2a9beb627a7.png)

2022-10-03 04:59 UTC, chilarai commented on A-Z-dropdown.html
>  <option value="s3">S3</option>
Thank you for that. Please resolve the conflicts and submit. Rest, I think its good to be merged

2022-10-04 04:30 UTC, merged